# Generated by Django 4.0.4 on 2022-06-01 08:52

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_rename_text_about1_about_history_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_image', models.FileField(blank=True, upload_to='background/services/', validators=[jobs.validators.validate_image_extension])),
                ('services_title', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
