# Generated by Django 4.0.4 on 2022-06-01 09:00

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='email_donate',
            new_name='services_name',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='facebook_link',
            new_name='services_name_ar',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='image_bg_donate',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='location_donate',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='location_donate_ar',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='phone_donate',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='donate',
            name='services_image',
            field=models.FileField(blank=True, upload_to='background/services/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
