# Generated by Django 4.0.4 on 2022-06-02 15:31

import datetime
from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_delete_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_image_one', models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[jobs.validators.validate_image_extension])),
                ('story_image_two', models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[jobs.validators.validate_image_extension])),
                ('story_image_three', models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[jobs.validators.validate_image_extension])),
                ('story_date', models.DateField(blank=True, default=datetime.date.today)),
                ('story_location', models.CharField(blank=True, default='', max_length=300)),
                ('story_name', models.CharField(blank=True, default='', max_length=300)),
                ('story_desc1', models.CharField(blank=True, default='', max_length=120)),
                ('story_desc2', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc3', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc4', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc5', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc6', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc7', models.TextField(blank=True, default='', max_length=1000)),
                ('story_location_ar', models.CharField(blank=True, default='', max_length=300)),
                ('story_name_ar', models.CharField(blank=True, default='', max_length=300)),
                ('story_desc1_ar', models.CharField(blank=True, default='', max_length=120)),
                ('story_desc2_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc3_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc4_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc5_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc6_ar', models.TextField(blank=True, default='', max_length=1000)),
                ('story_desc7_ar', models.TextField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ['-story_date'],
            },
        ),
    ]
