# Generated by Django 4.0.4 on 2022-06-02 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_storydetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='GetInvolved',
        ),
        migrations.DeleteModel(
            name='VisionMissionValue',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.DeleteModel(
            name='WhatWeAreDoingBackgroundImage',
        ),
        migrations.DeleteModel(
            name='WhatWeAreDoingDetail',
        ),
        migrations.DeleteModel(
            name='WhoWeAre',
        ),
    ]
