# Generated by Django 4.0.4 on 2022-06-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_delete_application_delete_getinvolved_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='Services',
        ),
    ]
