# Generated by Django 4.0.4 on 2022-06-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_rename_donate_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryDetail',
            new_name='ProjectDetail',
        ),
    ]
