# Generated by Django 4.0.4 on 2022-06-02 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_rename_storydetail_projectdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectDetail',
            new_name='StoryDetail',
        ),
    ]
