# Generated by Django 4.0.4 on 2022-06-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_rename_projectdetail_storydetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryDetail',
            new_name='ProjectDetail',
        ),
    ]
