# Generated by Django 4.0.4 on 2022-06-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_rename_services_image_services_services_image_bg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='services_image_bg',
            new_name='services_image',
        ),
    ]
