# Generated by Django 4.0.4 on 2022-06-03 11:41

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_rename_services_image_bg_services_services_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_bg_about',
            field=models.FileField(default='Some String', upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_middle_about',
            field=models.FileField(default='Some String', upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
