# Generated by Django 4.0.4 on 2022-06-03 11:55

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_about_image_bg_about_alter_about_image_middle_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image_bg_about',
            field=models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_middle_about',
            field=models.FileField(blank=True, null=True, upload_to='background/about/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
