# Generated by Django 4.0.4 on 2022-06-03 11:59

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_alter_about_image_bg_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='image_bg_project',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
