# Generated by Django 4.0.4 on 2022-06-03 12:02

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_projectdetail_image_bg_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_image_bg', models.FileField(blank=True, upload_to='background/services/', validators=[jobs.validators.validate_image_extension])),
            ],
        ),
    ]
