# Generated by Django 4.0.4 on 2022-06-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_aboutbackgroundimage_projectbackgroundimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
