# Generated by Django 4.0.4 on 2022-06-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectBackgroundImage',
        ),
    ]
