# Generated by Django 4.0.4 on 2022-06-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_delete_projectbackgroundimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='text_story_index',
            new_name='text_project_index',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='text_story_index_ar',
            new_name='text_project_index_ar',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_about_index',
        ),
        migrations.RemoveField(
            model_name='index',
            name='image_story_index',
        ),
    ]
