# Generated by Django 4.0.4 on 2022-06-03 14:54

from django.db import migrations, models
import jobs.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0032_rename_text_story_index_index_text_project_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='project_image_five',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[jobs.validators.validate_image_extension]),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='project_image_four',
            field=models.FileField(blank=True, default='', upload_to='background/stories_detail/', validators=[jobs.validators.validate_image_extension]),
        ),
    ]
