# Generated by Django 4.0.4 on 2022-06-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_projectdetail_project_image_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='project_image_five',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='project_image_four',
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='project_image_three',
        ),
    ]
