# Generated by Django 4.0.4 on 2022-06-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_remove_projectdetail_project_image_five_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='project_image_two',
        ),
    ]
